notifications:
  email: false
language: go
env:
  - GO111MODULE=on GOFLAGS=-mod=vendor
go:
- 1.12.x
- 1.13.x
sudo: false
env:
  - GO111MODULE=on
jobs:
  include:
  - stage: Unit tests
    script:
      - make test
